#! /bin/bash

set -e

basedir=$1
short=$2

# the dacapo benchmarks
dacapo=( antlr bloat chart hsqldb luindex lusearch pmd xalan)
dacapo=( "${dacapo[@]/#/dacapo/}" )

# the specjvm benchmarks
specjvm=( compress db jack javac jess raytrace )
specjvm=( "${specjvm[@]/#/specjvm/}" )

# put them all in one big array
benchmarks=( ${dacapo[@]} ${specjvm[@]} )

date
for benchmark in ${benchmarks[@]}
do
  echo "creating ${basedir}/${benchmark} ..."
  mkdir -p ${basedir}/${benchmark}
  touch ${basedir}/${benchmark}/${short}.stats
done
date