#! /bin/bash

set -e

basedir=$1
file=$2

# the dacapo benchmarks
dacapo=( antlr bloat chart hsqldb luindex lusearch pmd xalan)
dacapo=( "${dacapo[@]/#/dacapo/}" )

# the specjvm benchmarks
specjvm=( compress db jack javac jess raytrace )
specjvm=( "${specjvm[@]/#/specjvm/}" )

# put them all in one big array
benchmarks=( ${dacapo[@]} ${specjvm[@]} )

date
for i in ${!benchmarks[@]}
do
  benchmark=${benchmarks[$i]}
  index=$(($i+1))
  echo "copying to ${basedir}/${benchmark}/${file}.stats ..."
  echo `sed "${index}q;d" temp.stats` >> ${basedir}/${benchmark}/${file}.stats
done
date