#! /usr/bin/env bash

set -e

tool=$1
base=$3
benchmark=$4

##################################################################
if test "$2" = "-averroes"; then
  averroes=true
  toolname=${tool}-averroes
else
  averroes=false
  toolname=${tool}
fi

program=$(basename $benchmark)
outputdir=${base}/callgraphs/${toolname}-call-graphs/${benchmark}
doopdb=${outputdir}/database.tar.gz
cgfile=callgraph.txt.gzip
doopHome=/u/karim/workspace/doop
##################################################################

echo "running ${toolname} for ${benchmark}"

# 1. make some dirs
mkdir -p ${outputdir}/

# 2. run tool.jar
cp properties/${benchmark}.properties averroes.properties
jar uf tool.jar averroes.properties
java -verbose:gc -Xloggc:${outputdir}/${program}-gc.stats -jar tool.jar $doopHome $tool $base $benchmark $averroes

# 3. copy the call graph
cp output/${cgfile} ${outputdir}/${cgfile}

##################################################################
## Do some extra stuff for doop
##################################################################
if test "$tool" = "doop"; then
  # 4. copy database
  echo "making the database of ${toolname} available at ${doopdb} ..."
  tar -czf ${doopb} ../doop/last-analysis/*

  # 5. print disk usage
  echo -n "Disk usage stats: "
  du -sh ../doop/cache/analysis
fi

echo ""