#! /usr/bin/env bash

set -e

date
for i in {1..10}
do
  base=all-output/${i}
  echo "running for the ${i}th time!"
  echo "running Wala"
  ./wala-all ${base}
  echo " "
  echo " "
  echo " "
  echo " "
  echo " "
done
date