#! /usr/bin/env bash

set -e

date
  base=$1
  echo "running Averroes"
  ./averroes-all -enable-tamiflex ${base}
  echo "running Spark"
  ./spark-all ${base}
  echo "running SparkAverroes"
  ./spark-averroes-all ${base}
  echo "running Doop"
  ./doop-all ${base}
  echo "running DoopAverroes"
  ./doop-averroes-all ${base}
  echo "running Wala"
  ./wala-all ${base}
  echo "running WalaAverroes"
  ./wala-averroes-all ${base}
date