#! /bin/bash

# this file extract the statistics from the comparison files and put them in the respective stats file thesis-stats understands
set -e

basedir=callgraphs/comparisons-call-graphs
outputdir=statistics

# the dacapo benchmarks
dacapo=( antlr bloat chart hsqldb luindex lusearch pmd xalan)
dacapo=( "${dacapo[@]/#/dacapo/}" )

# the specjvm benchmarks
specjvm=( compress db jack javac jess raytrace )
specjvm=( "${specjvm[@]/#/specjvm/}" )

# put them all in one big array
benchmarks=( ${dacapo[@]} ${specjvm[@]} )

date

# First let's create some directories and  files
for benchmark in ${benchmarks[@]}
do
  mkdir -p ${outputdir}/spark/${benchmark}
  touch ${outputdir}/spark/${benchmark}/spark.stats
  
  mkdir -p ${outputdir}/spark-averroes/${benchmark}
  touch ${outputdir}/spark-averroes/${benchmark}/sparkave.stats
  
  mkdir -p ${outputdir}/doop/${benchmark}
  touch ${outputdir}/doop/${benchmark}/doop.stats
  
  mkdir -p ${outputdir}/doop-averroes/${benchmark}
  touch ${outputdir}/doop-averroes/${benchmark}/doopave.stats
  
  mkdir -p ${outputdir}/wala/${benchmark}
  touch ${outputdir}/wala/${benchmark}/wala.stats
  
  mkdir -p ${outputdir}/wala-averroes/${benchmark}
  touch ${outputdir}/wala-averroes/${benchmark}/walaave.stats
done

# Then let's copy edges count
for benchmark in ${benchmarks[@]}
do
  program=$(basename $benchmark)
  a2a=$(cat ${basedir}/${benchmark}/${program}-comparisons.stats | grep -m1 "Dynamic: " | tail -n1 | cut -f2- -d':')
  a2l=$(cat ${basedir}/${benchmark}/${program}-comparisons.stats | grep -m2 "Dynamic: " | tail -n1 | cut -f2- -d':')
  l2a=$(cat ${basedir}/${benchmark}/${program}-comparisons.stats | grep -m3 "Dynamic: " | tail -n1 | cut -f2- -d':')
  
  echo "application call graph edges =${a2a}" > ${basedir}/dynamic/${benchmark}/dyn.stats
  echo "library call graph edges =${a2l}" >> ${basedir}/dynamic/${benchmark}/dyn.stats
  echo "library call back edges =${l2a}" >> ${basedir}/dynamic/${benchmark}/dyn.stats
  
  
done


date