#! /usr/bin/env bash

set -e

reflection=$1
base=$2

# the dacapo benchmarks
dacapo=( antlr bloat chart hsqldb luindex lusearch pmd xalan )
dacapo=( "${dacapo[@]/#/dacapo/}" )

# the specjvm benchmarks
specjvm=( compress db jack javac jess raytrace )
specjvm=( "${specjvm[@]/#/specjvm/}" )

# put them all in one big array
benchmarks=( ${dacapo[@]} ${specjvm[@]} )

function timing()
{
	echo "..."
	/usr/bin/time -f "elapsed time: %es" $* 2>&1
}

date

for benchmark in ${benchmarks[@]}
do
  echo "running ${benchmark} ..."
  program=$(basename $benchmark)
  outputdir=${base}/benchmarks-averroes
  
  # 1. create output directory
  mkdir -p ${outputdir}/dacapo
  mkdir -p ${outputdir}/specjvm
  
  # 2. run the script
  timing ./averroes $benchmark $reflection $base > ${outputdir}/${program}-averroes.stats
done
date