#! /usr/bin/env bash

set -e

benchmark=$1
tamiflex=$2
base=$3

function timing()
{
	echo "..."
	/usr/bin/time -f "elapsed time: %es" $* 2>&1
}

date
outputdir=${base}/benchmarks-averroes

# make some dirs
mkdir -p ${outputdir}/dacapo
mkdir -p ${outputdir}/specjvm

echo "running ${benchmark}"
program=$(basename $benchmark)
  
# 1. run Averroes
cp properties/${benchmark}.properties averroes.properties
jar uf averroes.jar averroes.properties

if test "$2" = "-disable-tamiflex"; then
  timing java -jar averroes.jar $tamiflex
else
  timing java -jar averroes.jar
fi

# 2. copy the output JARs
cp output/organized-app.jar ${outputdir}/${benchmark}-organized-app.jar
cp output/organized-lib.jar ${outputdir}/${benchmark}-organized-lib.jar
cp output/placeholder-lib.jar ${outputdir}/${benchmark}-placeholder-lib.jar
cp output/averroes-lib-class.jar ${outputdir}/${benchmark}-averroes-lib-class.jar

echo ""