#! /usr/bin/env bash

set -e

date
for i in {1..10}
do
  base=all-output/${i}
  echo "running for the ${i}th time!"
  echo "running Averroes"
  ./averroes-all -disable-reflection ${base}
  echo " "
  echo " "
  echo " "
  echo " "
  echo " "
done
date