#! /usr/bin/env bash

set -e

date
for i in {1..10}
do
  base=all-output/${i}
  echo "running for the ${i}th time!"
  echo "running Averroes"
  #./averroes-all -disable-tamiflex ${base}
  ./averroes-all -enable-tamiflex ${base}
  echo "running Spark"
  ./spark-all ${base}
  echo "running SparkAverroes"
  ./spark-averroes-all ${base}
  echo "running Doop"
  ./doop-all ${base}
  echo "running DoopAverroes"
  ./doop-averroes-all ${base}
  echo "running Wala"
  ./wala-all ${base}
  echo "running WalaAverroes"
  ./wala-averroes-all ${base}
  echo " "
  echo " "
  echo " "
  echo " "
  echo " "
done
date