#! /usr/bin/env bash

set -e

tool=$1
averroes=$2
base=$3

##################################################################
if test "$averroes" = "-averroes"; then
  toolname=${tool}-averroes
else
  toolname=${tool}
fi
##################################################################

function timing()
{
	echo "..."
	/usr/bin/time -f "elapsed time: %es" $* 2>&1
}

# the dacapo benchmarks
dacapo=( antlr bloat chart hsqldb luindex lusearch pmd xalan)
dacapo=( "${dacapo[@]/#/dacapo/}" )

# the specjvm benchmarks
specjvm=( compress db jack javac jess raytrace )
specjvm=( "${specjvm[@]/#/specjvm/}" )

# put them all in one big array
benchmarks=( ${dacapo[@]} ${specjvm[@]} )

date
for benchmark in ${benchmarks[@]}
do
  program=$(basename $benchmark)
  outputdir=${base}/callgraphs/${toolname}-call-graphs/${benchmark} 
  
  # 1. create output directory
  mkdir -p ${outputdir}/
  
  # 2. run the script
  timing ./run-tool ${tool} ${averroes} ${base} ${benchmark} > ${outputdir}/${program}.stats
done
date